# inspired by: https://docs.github.com/en/actions/guides/publishing-docker-images
name: Publish Docker image To hub.docker

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: null

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # work around for npm installs from git+https://github.com/johannesjo/J2M.git
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
        with:
          images: johannesjo/super-productivity

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1

      - name: Save Docker image
        if: always()
        run: docker save --output super-productivity.tar johannesjo/super-productivity:${{ github.ref_name }}

      - name: Upload Docker image
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: super-productivity.tar
          retention-days: 1
